"use client";
import { useState, type FormEvent } from "react";
import { LoaderCircle, Save } from "lucide-react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { createCustomerAction, updateCustomerAction } from "@/app/actions/customers";
import type { Customer } from "@/data/customers";

type FormData = { name: string; company: string; email: string; phone: string; jobTitle: string; status: "ACTIVE" | "INACTIVE"; location: string; preferredContact: "Email" | "Phone"; notes: string };
const empty: FormData = { name: "", company: "", email: "", phone: "", jobTitle: "", status: "ACTIVE", location: "", preferredContact: "Email", notes: "" };
export function CustomerForm({ customer }: { customer?: Customer }) {
  const router = useRouter(); const [data, setData] = useState<FormData>(customer ? { name: customer.name, company: customer.company, email: customer.email, phone: customer.phone ?? "", jobTitle: customer.jobTitle ?? "", status: customer.status.toUpperCase() as FormData["status"], location: customer.location ?? "", preferredContact: customer.preferredContact === "Phone" ? "Phone" : "Email", notes: "" } : empty); const [errors, setErrors] = useState<Record<string, string>>({}); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const update = (key: keyof FormData, value: string) => setData((current) => ({ ...current, [key]: value }));
  async function submit(event: FormEvent) { event.preventDefault(); const next: Record<string, string> = {}; if (!data.name.trim()) next.name = "Full name is required."; if (!data.company.trim()) next.company = "Company is required."; if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email)) next.email = "Please enter a valid email address."; setErrors(next); if (Object.keys(next).length) return; setBusy(true); setError(""); try { const result = customer ? await updateCustomerAction(customer.id, data) : await createCustomerAction(data); router.push(customer ? `/customers/${result.id}` : "/customers"); } catch { setError("Unable to save customer. Please try again."); setBusy(false); } }
  const field = (key: keyof FormData, label: string, placeholder: string, type = "text") => <label className="form-field"><span>{label}{["name", "company", "email"].includes(key) && <b> *</b>}</span><input required={false} type={type} value={data[key]} onChange={(event) => update(key, event.target.value)} placeholder={placeholder} aria-invalid={Boolean(errors[key])} />{errors[key] && <small role="alert">{errors[key]}</small>}</label>;
  return <form className="customer-form" onSubmit={submit} noValidate><section className="customer-form-card"><div className="form-card-heading"><div><p>Profile details</p><h2>Customer information</h2></div><span className="form-required">* Required</span></div><div className="form-grid">{field("name", "Full name", "Enter customer's full name")}{field("company", "Company", "Enter company name")}{field("email", "Email address", "customer@example.com", "email")}{field("phone", "Phone number", "+1 (555) 000-0000", "tel")}{field("jobTitle", "Job title", "Customer Success Manager")}<label className="form-field"><span>Status</span><select value={data.status} onChange={(event) => update("status", event.target.value)}><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></label>{field("location", "Location", "City, State")}<label className="form-field"><span>Preferred contact method</span><select value={data.preferredContact} onChange={(event) => update("preferredContact", event.target.value)}><option>Email</option><option>Phone</option></select></label><label className="form-field full"><span>Notes</span><textarea value={data.notes} onChange={(event) => update("notes", event.target.value)} placeholder="Add any relevant customer notes..." /></label></div></section>{error && <p className="form-server-error" role="alert">{error}</p>}<div className="form-actions"><Button type="button" variant="outline" onClick={() => router.push("/customers")} disabled={busy}>Cancel</Button><Button type="submit" disabled={busy}>{busy ? <><LoaderCircle size={16} className="animate-spin" /> {customer ? "Updating customer..." : "Creating customer..."}</> : <><Save size={16} /> {customer ? "Update customer" : "Create customer"}</>}</Button></div></form>;
}